server.port=8080
spring.application.name=springboot-cicd

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=springboot-cicd
info.app.version=1.0.0
info.app.description=Spring Boot CI/CD demo
