import http from "k6/http";
import { check, sleep } from "k6";
import { Rate, Trend } from "k6/metrics";

const BASE_URL = __ENV.BASE_URL || "http://localhost:8080";
const DURATION = __ENV.DURATION || "30s";

const errorRate = new Rate("errors");
const taskApiTrend = new Trend("task_api_duration");

export const options = {
  stages: [
    { duration: "10s", target: 10 },   // ramp up
    { duration: DURATION, target: 50 }, // sustained load
    { duration: "10s", target: 0 },    // ramp down
  ],
  thresholds: {
    http_req_duration: ["p(95)<500"],  // 95% under 500ms
    http_req_failed:   ["rate<0.01"],  // <1% errors
    errors:            ["rate<0.05"],
  },
};

export default function () {
  // Health check
  const health = http.get(`${BASE_URL}/actuator/health`);
  check(health, { "health UP": (r) => r.status === 200 });
  errorRate.add(health.status !== 200);

  sleep(0.5);

  // List tasks
  const list = http.get(`${BASE_URL}/api/tasks?page=0&size=10`);
  check(list, {
    "list status 200": (r) => r.status === 200,
    "list has content": (r) => JSON.parse(r.body).content !== undefined,
  });
  taskApiTrend.add(list.timings.duration);
  errorRate.add(list.status !== 200);

  sleep(1);

  // Create task
  const payload = JSON.stringify({
    title: `Load test task ${Date.now()}`,
    description: "Generated by k6",
    status: "TODO",
    priority: "LOW",
  });
  const create = http.post(`${BASE_URL}/api/tasks`, payload, {
    headers: { "Content-Type": "application/json" },
  });
  check(create, { "create status 201": (r) => r.status === 201 });
  errorRate.add(create.status !== 201);

  sleep(1);
}
