apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-cicd-config
  namespace: springboot-cicd
data:
  SPRING_PROFILES_ACTIVE: "prod"
  JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"
  SERVER_PORT: "8080"
